language: python

sudo: false

python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"

env:
    - NO_STRIP=1
    - NO_STRIP=0

matrix:
    include:
        - python: "3.7"
          dist: xenial
          env: NO_STRIP=0
        - python: "3.7"
          dist: xenial
          env: NO_STRIP=1

addons:
    apt:
        packages:
        - rpm
        - enchant

install:
    - if [[ "$(python --version 2>&1)" =~ Python\ (2\.*) ]]; then pip install -U jinja2; else echo "Skipping JINJA2 for $(python --version 2>&1)."; fi
    - pip install -rtest-requirements.txt
    - pip install -e ./

script:
    - if [[ "$(python --version 2>&1)" =~ Python\ (2\.7.*|3\.[4-7].*) ]]; then pep8 rpmvenv/; else echo "Skipping PEP8 for $(python --version 2>&1)."; fi
    - if [[ "$(python --version 2>&1)" =~ Python\ (2\.7.*|3\.[4-7].*) ]]; then pyflakes rpmvenv/; else echo "Skipping PyFlakes for $(python --version 2>&1)."; fi
    - if [[ "${NO_STRIP}" == "1" ]]; then py.test -v --skip-binary-strip --python-git-url="https://github.com/kevinconway/rpmvenv_manylinux_issue.git" tests/; else py.test -v tests/; fi
