name: CI
on:
  push:
    branches:
      - "master"
    tags: ["*"]
  pull_request:
    branches:
      - "master"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkhout
        uses: actions/checkout@v2
      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Cache PyPI
        uses: actions/cache@v2
        with:
          key: pip-lint-${{ hashFiles('requirements.txt', 'test-requirements.txt') }}
          path: ~/.cache/pip
          restore-keys: |
            pip-lint-
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r test-requirements.txt
      - name: pep8
        run: |
          pycodestyle rpmvenv/
          pycodestyle tests/
      - name: pyflakes
        run: |
          pyflakes rpmvenv/
          pyflakes tests/
  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyver: ["3.7", "3.8", "3.9", "3.10", "3.11"]
      fail-fast: true
    steps:
      - name: Install deps
        run: sudo apt update && sudo apt install -y rpm enchant-2
      - name: Checkhout
        uses: actions/checkout@v2.4.0
      - name: Setup Python ${{ matrix.pyver }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.pyver }}
      - name: Cache PyPI
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.pyver }}-${{ hashFiles('test-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.pyver }}-
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          python -m pip install -r test-requirements.txt
          python -m pip install -e ./
      - name: Run tests
        env:
          PYTHONPATH: .
        run: |
          py.test -v --python_ver="python${{ matrix.pyver }}" --skip-binary-strip --python-git-url="https://github.com/kevinconway/rpmvenv_manylinux_issue.git" tests/
          py.test -v --python_ver="python${{ matrix.pyver }}" --python-git-url="https://github.com/kevinconway/rpmvenv_manylinux_issue.git" tests/
  build-and-publish:
    name: Build and publish
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install pypa/build
        run: python -m pip install build
      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/ .
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
